### ISSUE TITLE
Ruby 2.3.3 >> having issues with mini_magick

### ISSUE THREAD

**Issue by rbojjasba** [samnissen/watir-screenshot-stitch#22]
```
.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:208:in `rescue in validate!': ImageMagick/GraphicsMagick is not installed (MiniMagick::Invalid)
	from /Users/r/.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:206:in `validate!'
	from /Users/r/.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:118:in `block in create'
	from /Users/r/.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:117:in `tap'
	from /Users/r/.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:117:in `create'
	from /Users/r/.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:34:in `read'
	from /Users/r/Downloads/watir-screenshot-stitch-master/lib/watir-screenshot-stitch.rb:84:in `bug_shot?'
	from /Users/r/Downloads/watir-screenshot-stitch-master/lib/watir-screenshot-stitch.rb:60:in `base64_canvas'
	from /Users/r/Downloads/watir-screenshot-stitch-master/stitich.rb:14:in `<top (required)>'a
```

**Comment by rbojjasba** [comment]
solved it after this brew command >> brew install graphicsmagick
