### ISSUE TITLE
Binding of caller dependencies incompatible with pry-stack-explorer

### ISSUE THREAD

**Issue by EthanZeigler** [samnissen/watir-screenshot-stitch#65]
**Description**
watir-screenshot-stitch depends on `binding-of-caller ~> 0.7`, which makes it incompatible with pry-stack-explorer's `binding-of-caller ~> 1.0` This makes debugging selenium based projects difficult.

**Ask**
Upgrade binding of caller dependency to make compatible with pry-stack-explorer

**Comment by MatrixFr** [comment]
I must comment your gem in my gemfile, I have an error if not :+1: 

`path/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- binding_of_caller.so (LoadError)`

Its probably the same problem as you @EthanZeigler , so I post here instead of create a new topic...

**Comment by EthanZeigler** [comment]
> I must comment your gem in my gemfile, I have an error if not 👍
> 
> `path/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- binding_of_caller.so (LoadError)`
> 
> With` rails (6.1.4.1)`
> 
> Its probably the same problem as you @EthanZeigler , so I post here instead of create a new topic...

It's almost certainly a different problem. I'm describing a dependency version mismatch. What you have is probably a bad installation.
